### ISSUE TITLE
usewgridder no effective from wsclean v3.4 onwards

### ISSUE THREAD

**Issue by botteon** [rvweeren/lofar_facet_selfcal#115]
Hi,

just to point out that `--usewgridder` has no effect if wsclean v3.4 is used, as since this version wgridder is the default gridder: you will end up using wgridder in facetselfcal even without setting `--usewgridder`  in the parser!

**Comment by rvweeren** [comment]
Yeh, I'll remove it from the option list in the next update round.

**Comment by botteon** [comment]
What about a `--gridder` option which is set to wgridder by default? Instead of `--usewgridder` and `--idg` one could just have to set `--griddger wgridder` and `--gridder idg`. By looking at the code, this should be doable.
In some wsclean versions, wgridder does not work if channel frequencies are sorted in descending order (e.g. in the GMRT), so one has to use wstacking. I think that this issue was solved in the current wsclean, but this edit would make the code work also with older wsclean versions. Now the usage of the gridder is ambiguous in facetselfcal because it depends on the wsclean version used...
Generally, at some point the code should check at the beginning of the run that the wsclean in the system is not too old...
