### ISSUE TITLE
Default for --ncpu-max-DP3solve differs from description.

### ISSUE THREAD

**Issue by tikk3r** [rvweeren/lofar_facet_selfcal#133]
The help for the --ncpu-max-DP3solve mentions the default is 24, but the default value set in the parser is 64.

I also see a notable speedup in scalarphase solves by dropping it from 64 to 24, so I guess it is supposed to be the 24?

**Comment by rvweeren** [comment]
>I also see a notable speedup in scalarphase solves by dropping it from 64 to 24, so I guess it is supposed to be the 24?
Interesting, I thought that recently DP3 was supposed to be better with using all cores?

**Comment by tikk3r** [comment]
> > I also see a notable speedup in scalarphase solves by dropping it from 64 to 24, so I guess it is supposed to be the 24?
> 
> Interesting, I thought that recently DP3 was supposed to be better with using all cores?

This is what I see on a subset of the same MS with `msin.ntimes=100` but otherwise the same:
```bash
numthreads=64
real    2m17.187s
user    14m33.477s
sys 85m51.712s

numthreads=32
real    1m35.429s
user    11m49.795s
sys 22m18.627s

numthreads=24
real    1m22.932s
user    10m13.597s
sys 11m53.605s

numthreads=64 + taskset -c 0-94:2
real    1m59.519s
user    13m14.467s
sys 38m58.404s

numthreads=32 + taskset -c 0-94:2
real    1m24.043s
user    12m1.338s
sys 16m39.630s

numthreads=24 + taskset -c 0-94:2
real    1m15.758s
user    10m18.020s
sys 9m6.337s
```

I don't think the amount of time fed to it matters for parallelization, since `ntimes=200` shows a similar difference, so a lower core count seems worth it for at least the scalarphase ones.

**Comment by rvweeren** [comment]
Wow, 85min vs 11min is a major difference! Your results suggest that lowering numthreads to below 24 it might be even take less time? numthreads=16 or numthreads=12?

**Comment by tikk3r** [comment]
Not quite as dramatic, it's the `real` entry of those times that show the actual time of the run. So it goes from 2m17 to 1m22, but still a nice difference. For this particular command 12 seems to be the sweetspot. At 8 it got slower again.

```
numthreads=16 + taskset -c 0-94:2
real    1m11.332s
user    9m42.543s
sys 2m52.065s

numthreads=12 + taskset -c 0-94:2
real    1m2.180s
user    7m22.735s
sys 1m11.407s

numthreads=8 + taskset -c 0-94:2
real    1m10.803s
user    6m49.168s
sys 0m11.870s
```

**Comment by rvweeren** [comment]
For a scalarcomplexgain solve (multi-dir; 10 directions, different solints per dirction) the scaling is quite different, see below. I guess, depending on the type of solves we could adjust numthreads. But it would require a bit more investigation to get a more complete picture how numthreads affects the runtime. I do think that in general phase-type solves work better if numthreads is not too high, while (scalar)complexgain can handle larger numthreads. It is not clear to me yet how the multi-dir aspect influences this.

For very demanding calibration runs, that take several days it might be worthwhile to spend say an hour or so on finding the optimal settings. Maybe one could make a function in facetselfcal that does some grid search and then returns the optimal numthreads for each of the solves employed in facetselfcal. 

((You could also make the argument that DP3 needs to be improved/be smarter in this repsect, not sure if one can expect users to deal with the intricacies of DP3 numthreads behaviour)) 


```
numthreads=96
real	1m23.210s
user	43m23.857s
sys	0m34.250s

numthreads=64
real	1m30.329s
user	48m31.326s
sys	0m20.805s

numthreads=36
real	1m24.805s
user	26m33.847s
sys	0m12.199s

numthreads=24
real	1m27.405s
user	19m37.433s
sys	0m10.562s

numthreads=16
real	1m39.505s
user	17m12.507s
sys	0m10.067s

numthreads=12
real	1m51.474s
user	16m23.322s
sys	0m8.502s



```

**Comment by rvweeren** [comment]
Completely opposite from what you found, with task `set -c 0-94:2` I get a significant slowdown for this mulit-dir scalarcomplexgain solve (lower numthreads reduce runtime slightly now, but runtime is significant longer overall still without the `taskset -c 0-94:2`)

```
numthreads=64 + taskset -c 0-94:2
real	2m0.070s
user	62m41.463s
sys	0m10.489s

numthreads=36 + taskset -c 0-94:2
real	1m57.509s
user	42m30.431s
sys	0m7.506s

numthreads=24 + taskset -c 0-94:2
real	1m49.483s
user	28m38.611s
sys	0m6.549s


```

**Comment by tikk3r** [comment]
Hmm, rerunning them today I see only a small difference in performance between 12 or 32 or 96 cores, which is more in line with what you found:
```
scalarphase ntimes=100 numthreads=12 solint=1
Total DP3 time      28.41 real       185.1 user        5.52 system

scalarphase ntimes=100 numthreads=32 solint=1
Total DP3 time       29.6 real      272.94 user       10.39 system

scalarphase ntimes=100 numthreads=96 solint=1
Total DP3 time      32.69 real      403.74 user       42.77 system
```
so indeed something to look into more carefully.

I'll close the ticket since the parameter-help mismatch is resolved.
