### ISSUE TITLE
Model images not found for channelsout=1

### ISSUE THREAD

**Issue by tikk3r** [rvweeren/lofar_facet_selfcal#134]
Probably a bit more of a niche case, but I ran into an issue regarding the model images for `channelsout=1`. The first crash was in `checkforzerocleancomponents`, for which the call is hardcoded to look for channel images:

https://github.com/rvweeren/lofar_facet_selfcal/blob/73c04c872112d0b765ff21e84c0bf562b62d42e5/facetselfcal.py#L7237-L7241

I changed it to something like
```python
        if channelsout > 1: 
            checkforzerocleancomponents(glob.glob(imageout + '-????-*model*.fits'))
        else:
            checkforzerocleancomponents(glob.glob(imageout + '-*model*.fits'))
```

but a restart also crashes with the following:
```python
Traceback (most recent call last):
  File "/cosma8/data/do011/dc-swei1/CasA/L2040577/selfcal_core/../lofar_facet_selfcal/facetselfcal.py", line 9842, in <module>
    main()
  File "/cosma8/data/do011/dc-swei1/CasA/L2040577/selfcal_core/../lofar_facet_selfcal/facetselfcal.py", line 9519, in main
    fitsmask, fitsmask_list = set_fitsmask_restart(args, i, mslist)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cosma8/data/do011/dc-swei1/CasA/L2040577/selfcal_core/../lofar_facet_selfcal/facetselfcal.py", line 9040, in set_fitsmask_restart
    fitsmask = fitsmask.replace('-MFS', '').replace('-I','')
               ^^^^^^^^
UnboundLocalError: cannot access local variable 'fitsmask' where it is not associated with a value
```

So I think there are a few places that assume there are channel images.

**Comment by rvweeren** [comment]
There is a proposed fix in rvweeren-patch-16, can you test if that solves the issue?

**Comment by tikk3r** [comment]
That fixed the resume issue. It's just `checkforzerocleancomponents` and such that need the same check it still.

**Comment by rvweeren** [comment]
Fixed the channelsout=1 and checkforzerocleancomponents issue.
