### ISSUE TITLE
Remove datasets if they become fully  flagged

### ISSUE THREAD

**Issue by twshimwell** [rvweeren/lofar_facet_selfcal#17]
Hey,

When running with --usemodeldataforsolints and using many short datasets sometimes a dataset will get completely flagged and auto_determinesolints fails, like e.g.

Successful readonly open of default-locked table GJ_GJ.dysco.sub.shift.avg.weights.ms.archive0.copy/SPECTRAL_WINDOW: 14 columns, 1 rows
Successful readonly open of default-locked table GJ_GJ.dysco.sub.shift.avg.weights.ms.archive0.copy: 29 columns, 1486047 rows
(1486047, 3)
Compute visibility noise of the dataset with robust sigma clipping GJ_GJ.dysco.sub.shift.avg.weights.ms.archive0.copy
Integration time visibilities 16.022241592407227
Noise visibilities: -- Jy
Flux in model: -- Jy
UV-selection to compute model flux: 40.013155733078605 km
-- Using tec(andphase) solint: --
Using tec(andphase) solint [s]: nan
Traceback (most recent call last):
  File "/home/shimwell/Software/GJ/facetselfcal.py", line 4766, in <module>
    main()
  File "/home/shimwell/Software/GJ/facetselfcal.py", line 4687, in main
    auto_determinesolints(mslist, args['soltype_list'], \
  File "/home/shimwell/Software/GJ/facetselfcal.py", line 2143, in auto_determinesolints
    insolint_list[soltype_id][ms_id] = np.int(solint)

Wondering if it'd be worth logging the flagging fractions and automatically identifying and removing datasets that become flagged through the procedure? E.g. like 

def check_flagged(ms):
    t = pt.table(ms, readonly=True)
    tc = t.getcol('FLAG').flatten()
    return float(np.sum(tc))/len(tc)

**Comment by rvweeren** [comment]
>a dataset will get completely flagged
@twshimwell, you mean it gets flagged by the facetselfcal script? (or it was already flagged at the input?) If the script flags the dataset we need to figure out why the dataset gets flagged... (there might be some assumptions in the code that relate to the number of time solution intervals and that could cause issues)

**Comment by twshimwell** [comment]
Yeh it gets completely flagged during the selfcal when doing the first one with amplitudes. The file GJ393_GJ393.dysco.sub.shift.avg.weights.ms.archive0 is about 60% flagged but GJ393_GJ393.dysco.sub.shift.avg.weights.ms.archive0.copy is 100% flagged. I've put a full log of the run on https://www.dropbox.com/s/y7eaozcx4m6o6qw/GJ393-selfcal.out?dl=0

**Comment by twshimwell** [comment]
All the solutions are in /disks/paradata/shimwell/solutions.tar. Yeh im using --auto but ive also tried adding some other options to reduce the flagging, so this particular log and solution set is from adding also:

--flagslowamprms=20 --auto --restoreflags --doflagging=False --usemodeldataforsolints.

**Comment by rvweeren** [comment]
@twshimwell can you share the plots (you shared the h5...not the plota)

**Comment by twshimwell** [comment]
Ah sorry yes. These are in /disks/paradata/shimwell/solution_plots

**Comment by rvweeren** [comment]
The issue seems actually not related to the script but DP3. There is so much flagged data in your ms.achive0 that the scalarcomplex gain solve return only invalid solutions (NaNs). What I see is that in many ms already 50% or so of all timeslots are fully flagged (so there are long (hr+) periods of fully flagged data, for some reason always at the start or end of a ms). To solve this issue these long periods will need to be removed from the ms. (with the benefit you need 50% less diskspace....)

**Comment by rvweeren** [comment]
Maybe someone already wrote a script to find fully flagged time periods at the start/end of a ms? (I can then easily add this to my script....)

**Comment by rvweeren** [comment]
fixed
