### ISSUE TITLE
Hardcoded paths to Leiden nodes

### ISSUE THREAD

**Issue by cgroeneveld** [rvweeren/lofar_facet_selfcal#2]
https://github.com/rvweeren/lofar_facet_selfcal/blob/dde0c03e5181744b91ad5a4ef3bae348bd88e2e9/facetselfcal.py#L3263

seems that there are still some hardcoded paths to Leiden nodes, not sure what a good solution would be. Maybe this can be replaced with --helperscripath or a separate option

**Comment by rvweeren** [comment]
this is special testing code to manually manipulate clean components, not used at the moment in the script (because there is an if False statement there). I like to keep it as an example so we can re-use it if needed at some point.
