### ISSUE TITLE
calling supporting scripts

### ISSUE THREAD

**Issue by ggurkan** [rvweeren/lofar_facet_selfcal#26]
Supporting scripts (BLsmooth.py  lib_multiproc.py  lin2circ.py  plot_tecandphase.py) are now in args['helperscriptspath'] + /supporting_scripts/reinout/ so just required to add "+ /supporting_scripts/reinout/" in lines 4791, 4800, 4801,4802.

**Comment by rvweeren** [comment]
I do not think there is an issue here but reopen if needed
