### ISSUE TITLE
h5_merger.py is expected in helperscript path

### ISSUE THREAD

**Issue by lmorabit** [rvweeren/lofar_facet_selfcal#3]
The --helperscriptpath can be used to point to wherever this repository is cloned, but the facetselfcal.py script expects h5_merger.py to also be there.  Perhaps another argument can be provided for the path to the h5_merger.py script.

**Comment by rvweeren** [comment]
implemented via --helperscriptpath-h5merger (if not given it uses helperscriptpath)
