### ISSUE TITLE
Issue with phasedup variable if no beam correction is performed

### ISSUE THREAD

**Issue by JonnyPierce** [rvweeren/lofar_facet_selfcal#38]
We ran into an issue when running facetselfcal.py, related to the phasedup variable. The variable is undefined if no beam correction is performed (i.e. if beam = False), causing the code to crash. A quick fix we implemented was to add phasedup=False in a line just before "if beam" (line 3493), so that the variable is still assigned in such cases.

https://github.com/rvweeren/lofar_facet_selfcal/blob/55bbc5e155f9eb9aa4affdc192c14ea0a02b56eb/facetselfcal.py#L3493-L3494

**Comment by rvweeren** [comment]
Yes that is a (new) bug, testing a fix now.
