### ISSUE TITLE
Removing the Software Checks if Paths to scripts already specified

### ISSUE THREAD

**Issue by jwpetley** [rvweeren/lofar_facet_selfcal#53]
A lot of work in Durham is done on our COSMA computing cluster which does not have internet access on the compute nodes. We are losing quite a lot of time every time we run this script as the `check_code_is_uptodate` function always even if we have specified the lofar helper scripts paths when using the script. Could we avoid calling this function if these paths are specified (i.e we do not want and don't need to download the latest versions)? 

We are losing 10-20 minutes every time we run this script as it tries and fails to connect to github ~10 times for the repositories.

**Comment by rvweeren** [comment]
Yes, it should be relatively easy to add a  switch that skips the check_code_is_uptodate.

**Comment by rvweeren** [comment]
done
