### ISSUE TITLE
selfcal not convering issue

### ISSUE THREAD

**Issue by AlexKurek** [rvweeren/lofar_facet_selfcal#65]
Just reporting: Im getting this:
```
Traceback (most recent call last):
  File "/storage/akurek/extractPy/4C29.30/4C29.30/./lofar_facet_selfcal/facetselfcal.py", line 41, in <module>
    import bdsf
  File "/home/akurek/.local/lib/python3.10/site-packages/bdsf/__init__.py", line 33, in <module>
    from .wavelet_atrous import Op_wavelet_atrous
  File "/home/akurek/.local/lib/python3.10/site-packages/bdsf/wavelet_atrous.py", line 36, in <module>
    import pyfftw.interfaces
  File "/usr/local/lib/python3.10/dist-packages/pyfftw/__init__.py", line 43, in <module>
    from . import interfaces
  File "/usr/local/lib/python3.10/dist-packages/pyfftw/interfaces/__init__.py", line 279, in <module>
    from dask.array.fft import fft_wrap
  File "/usr/local/lib/python3.10/dist-packages/dask/array/__init__.py", line 2, in <module>
    from dask.array import backends, fft, lib, linalg, ma, overlap, random
  File "/usr/local/lib/python3.10/dist-packages/dask/array/backends.py", line 18, in <module>
    from dask.array.percentile import _percentile
  File "/usr/local/lib/python3.10/dist-packages/dask/array/percentile.py", line 9, in <module>
    from dask.array.core import Array
  File "/usr/local/lib/python3.10/dist-packages/dask/array/core.py", line 37, in <module>
    from dask.array.chunk_types import is_valid_array_chunk, is_valid_chunk_type
  File "/usr/local/lib/python3.10/dist-packages/dask/array/chunk_types.py", line 122, in <module>
    import sparse
  File "/usr/local/lib/python3.10/dist-packages/sparse/__init__.py", line 1, in <module>
    from ._coo import COO, as_coo
  File "/usr/local/lib/python3.10/dist-packages/sparse/_coo/__init__.py", line 1, in <module>
    from .core import COO, as_coo
  File "/usr/local/lib/python3.10/dist-packages/sparse/_coo/core.py", line 9, in <module>
    import numba
  File "/usr/local/lib/python3.10/dist-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/usr/local/lib/python3.10/dist-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/usr/local/lib/python3.10/dist-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```
After downgrading numpy to 1.23.5 this disappears. I was able tu run it by:
`pip install astropy numpy==1.23.5 bdsf losoto matplotlib pyregion tables astroquery everybeam tqdm joblib dill psutil aplpy python-magic`
and then:
`python ./lofar_facet_selfcal/facetselfcal.py --auto --helperscriptspath "/storage/akurek/extractPy/4C29.30/4C29.30/lofar_facet_selfcal" --helperscriptspathh5merge "/storage/akurek/extractPy/4C29.30/4C29.30/lofar_helpers" --losotobeamcor-beamlib everybeam -b 4C29.30.ds9.reg -i 4C29.30.fits *.dysco.sub.shift.avg.weights.ms.archive?`
I had to supply `helperscriptspath ` and `helperscriptspathh5merge`. Supplying `PYTHONPATH` to these folders did not work.

**Comment by tikk3r** [comment]
NumPy 1.24 seems to be a bit problematic in general, so it's probably best to avoid that for a bit.

**Comment by AlexKurek** [comment]
Now Im getting:
```
-- Using tec(andphase) solint: --
Using tec(andphase) solint [s]: nan
Traceback (most recent call last):
  File "/storage/akurek/extractPy/4C29.30/4C29.30/./lofar_facet_selfcal/facetselfcal.py", line 6463, in <module>
    main()
  File "/storage/akurek/extractPy/4C29.30/4C29.30/./lofar_facet_selfcal/facetselfcal.py", line 6375, in main
    auto_determinesolints(mslist, args['soltype_list'], \
  File "/storage/akurek/extractPy/4C29.30/4C29.30/./lofar_facet_selfcal/facetselfcal.py", line 3357, in auto_determinesolints
    insolint_list[soltype_id][ms_id] = np.int(solint)
  File "/home/akurek/facetSC-venv/lib/python3.10/site-packages/numpy/ma/core.py", line 4429, in __int__
    raise MaskError('Cannot convert masked element to a Python int.')
numpy.ma.core.MaskError: Cannot convert masked element to a Python int.
```
This is from numpy 1.23.5 installed in venv.

**Comment by AlexKurek** [comment]
Now Im getting:
```
Traceback (most recent call last):
  File "/storage/akurek/extractPy/4C29.30/4C29.30/./lofar_facet_selfcal/facetselfcal.py", line 6463, in <module>
    main()
  File "/storage/akurek/extractPy/4C29.30/4C29.30/./lofar_facet_selfcal/facetselfcal.py", line 6375, in main
    auto_determinesolints(mslist, args['soltype_list'], \
  File "/storage/akurek/extractPy/4C29.30/4C29.30/./lofar_facet_selfcal/facetselfcal.py", line 3357, in auto_determinesolints
    insolint_list[soltype_id][ms_id] = np.int(solint)
  File "/home/akurek/facetSC-venv/lib/python3.10/site-packages/numpy/ma/core.py", line 4429, in __int__
    raise MaskError('Cannot convert masked element to a Python int.')
numpy.ma.core.MaskError: Cannot convert masked element to a Python int.
```
Full log attached: [log_Facetselfcal.zip](https://github.com/rvweeren/lofar_facet_selfcal/files/11182618/log_Facetselfcal.zip)

**Comment by rvweeren** [comment]
The reason for the last error is that P129+29_4C29.30.dysco.sub.shift.avg.weights.ms.archive0 gets close to 100% flagged after the first DP3 solve (there is no remaining good data above a uv distance of 40km and hence you get NaNs from the visibility noise computation. Check the input file, it might be compromised (either a lot of data was flagged at the start, or there could be a problem with the weights, hard to say without a detailed look). Options to spot this is to use rfigui on the P129+29 archive0 ms and also have a look at the solutions plots for P129+29 (both beam and the tec/phase ones) and check if you spot something misbehaving.

(btw noted that P130+32_4C29.30.dysco.sub.shift.avg.weights.ms.archive0 is much nosier than the other two sets, probably because it was pointed far away from the target, so adding it might not really help much)

**Comment by AlexKurek** [comment]
@rvweeren Thank you, I learned a lot from this.
Using default settings `extraction.py 4C29.30` downloads all 3 fields.
"Standard" selfacl is able to process all 3 fields, its not crsshing.
Now I took only the other field, `MS0839.8+2938_4C29.30.dysco.sub.shift.avg.weights.ms.archive0`, and ran both standard and facet selfcal on it. These are the results. Standard on the left, facet on the right.
![Clipboard01](https://user-images.githubusercontent.com/45330694/230775991-93068d1b-b7de-4968-9974-919a8d3eaf7a.jpg)

**Comment by AlexKurek** [comment]
I just finished another two. NGC 4449 (up) looks worse than originally (more radial artefacts) and NGC 6949 (down) looks better.
Why does 4C29.30 and NGC 4449 look so bad, am I doing something wrong?

![N4449_009](https://user-images.githubusercontent.com/45330694/230935725-a8f7e938-149e-4810-b182-0f472c41fad0.png)

![N6946_009_fits](https://user-images.githubusercontent.com/45330694/230935777-d8ac4f4d-e57e-411d-8301-7884600785f1.jpg)

**Comment by rvweeren** [comment]
> look so bad, am I doing something wrong?
Clearly, something did not go right (almost as if no calibration happened) but that's all I can say from looking at the images.

**Comment by AlexKurek** [comment]
I updated both lofar_facet_selfcal and h5_merger.py to current master and re-ran both targets. The maps look the same. I attach logs for both.
[4C29.30.zip](https://github.com/rvweeren/lofar_facet_selfcal/files/11233890/4C29.30.zip)
[NGC4449.zip](https://github.com/rvweeren/lofar_facet_selfcal/files/11234240/NGC4449.zip)

**Comment by rvweeren** [comment]
Thanks for these logs. I do not directly see any real errors in these logs. The one thing that I do find strange is the:

```
Iterations taken: [3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2,3|2]
    0.0% (    0 ms) MSUpdater msout.
```

That could indicate that DP3 thinks the solutions converged, while in fact, this did not happen (and then the image does not improve at all during the selfcal). Could you put the 4C29.30 (assuming this one is smaller than the NGC4449 set) input ms somewhere where I can download it to test/debug?

BTW To confirm the DP3 solutions are the problem can you show the plots: merged_selfcalcyle000ampdirDir00_polXX.png merged_selfcalcyle000phasedirDir00_polXX.png plots? (in the plotlosoto<msname> folder)

**Comment by AlexKurek** [comment]
I uploaded it here:
http://byk.oa.uj.edu.pl/~akurek/
There are no png files with exactly the same name, so I also uploaded the entire plotlosoto folder.

**Comment by rvweeren** [comment]
The plots confirm what I suspected. The DP3 phase(/tec) solutions are close to 0 rad and the amplitudes are 1.0. So this means that essentially nothing happens during the selfcal and there is no improvement.

**Comment by rvweeren** [comment]
Doing a facetselfcal run now to see if I can reproduce the issue....

**Comment by AlexKurek** [comment]
I just found that I had:
`--losotobeamcor-beamlib everybeam`
which is not correct accoriding to:
https://github.com/rvweeren/lofar_facet_selfcal/blob/main/facetselfcal.py#L6180
The script was not crashing becouse of this. Now checking the default value.
BTW there is a typo in this line: stationreponse ;)

**Comment by AlexKurek** [comment]
I removed this from my run script:
`--losotobeamcor-beamlib everybeam`
and it crashed saying:
```
DP3 numthreads=24 msin=MS0839.8+2938_4C29.30.dysco.sub.shift.avg.weights.ms.archive0.copy msin.datacolumn=DATA msout=. msin.modelcolumn=DATA steps=[ddecal] ddecal.type=ddecal ddecal.maxiter=1 ddecal.usemodelcolumn=True ddecal.nchan=1 ddecal.mode=complexgain ddecal.h5parm=MS0839.8+2938_4C29.30.dysco.sub.shift.avg.weights.ms.archive0.copy_templatejones.h5 ddecal.solint=10
Traceback (most recent call last):
  File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 6645, in <module>
    main()
  File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 6424, in main
    beamcor_and_lin2circ(ms, dysco=args['dysco'], \
  File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 4139, in beamcor_and_lin2circ
    losotolofarbeam(H5name, 'phase000', ms, useElementResponse=False, useArrayFactor=True, useChanFreq=True, beamlib=losotobeamlib)
  File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 2548, in losotolofarbeam
    from lofar.stationresponse import stationresponse
ModuleNotFoundError: No module named 'lofar'
Closing remaining open files:MS0839.8+2938_4C29.30.dysco.sub.shift.avg.weights.ms.archive0.copy_templatejones.h5...done
```

**Comment by tikk3r** [comment]
> I removed this from my run script: `--losotobeamcor-beamlib everybeam` and it crashed saying:
> 
> ```
> DP3 numthreads=24 msin=MS0839.8+2938_4C29.30.dysco.sub.shift.avg.weights.ms.archive0.copy msin.datacolumn=DATA msout=. msin.modelcolumn=DATA steps=[ddecal] ddecal.type=ddecal ddecal.maxiter=1 ddecal.usemodelcolumn=True ddecal.nchan=1 ddecal.mode=complexgain ddecal.h5parm=MS0839.8+2938_4C29.30.dysco.sub.shift.avg.weights.ms.archive0.copy_templatejones.h5 ddecal.solint=10
> Traceback (most recent call last):
>   File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 6645, in <module>
>     main()
>   File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 6424, in main
>     beamcor_and_lin2circ(ms, dysco=args['dysco'], \
>   File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 4139, in beamcor_and_lin2circ
>     losotolofarbeam(H5name, 'phase000', ms, useElementResponse=False, useArrayFactor=True, useChanFreq=True, beamlib=losotobeamlib)
>   File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 2548, in losotolofarbeam
>     from lofar.stationresponse import stationresponse
> ModuleNotFoundError: No module named 'lofar'
> Closing remaining open files:MS0839.8+2938_4C29.30.dysco.sub.shift.avg.weights.ms.archive0.copy_templatejones.h5...done
> ```

Could just be a small installation issue. Do you have [LOFARBeam](https://github.com/lofar-astron/LOFARBeam), which provides stationresponse, installed?

Additionally, in the containers we generally use this is installed under a sort of dummy `lofar` module to not break compatibility with other/older things that assume it is installed as part of the full `lofar` package instead of standalone (see [here](https://github.com/tikk3r/flocs/blob/5c2f23a9081c7be6b0873f2fe6fb8ba7d1234df8/singularity/Singularity.intel_mkl#L508-L526)).

**Comment by AlexKurek** [comment]
I just installed LOFARBeam and still getting this issue. For me its OK, I can keep doing
`--losotobeamcor-beamlib everybeam`

**Comment by rvweeren** [comment]
I do get a correctly coverging selfcal for 4C29.30 (with images improving nicely), so the conclusion is that the  issue is related to your specific DP3 version/installation. It is not related to facetselfcal. This can also be noticed by the number of iterations reported during the DP3 solve. In my case, I have:

```
Iterations taken: [49|17,101|30,69|20,60|22,101|26,63|18,56|14,50|19,49|18,54|14,47|19,53|19,46|16,50|20,49|17,43|17,44|16,53|20,67|36,47|20,48|16,101|16,101|15,45|15,42|16,46|17,49|18,47|17,67|18,45|16,53|21,82|46,74|46,42|16,44|16,49|16,48|21,44|18,61|17,101|16,80|46,49|18,45|15,101|16,52|19,54|17,48|17,42|16,58|15,40|15,41|16,42|13,46|19,52|18,42|17,45|16,44|16,42|15,75|46,41|16,43|19,41|16,43|15,39|14,38|14,57|18,42|15,87|16,40|16,45|17,38|14,46|16,44|17,46|16,42|15,46|16,39|15,40|14,40|18,38|15,39|14,42|15,45|14,41|15,38|14,39|15,46|17,50|21,41|12,41|13,38|11,37|14,39|16,101|12,37|12,38|15,41|18,40|14,40|18,39|16,38|13,44|19,41|16,39|17,40|15,43|18,35|12,45|14,40|12,38|13,42|18,38|12,32|12,36|13,38|14,31|11,45|14,39|16,47|14,34|12,36|15,35|11,41|17,34|13,33|9,34|11,36|14,40|19,36|12,36|11,40|14,35|12,41|14,40|13,38|15,42|14,37|13,34|12,37|12,36|12,38|13,64|42,53|26,37|12,34|12,32|12,37|13,40|14,42|15,34|13,42|13,38|15,36|13,40|15,39|14,40|13,38|13,41|13,34|12,38|12,39|14,39|15,34|12,36|12,44|12,41|13,35|12,33|11,37|11,40|14,35|13,32|12,37|14,37|13,42|16,37|14,37|13,38|14,38|13,35|13,34|11,32|10,34|9,39|12,40|13,39|13,36|13,37|11,34|12,39|16,36|12,35|14,33|12,38|12,36|13,36|12,36|12,38|12,36|14,38|12,46|20,36|12,41|14,38|13,39|13,36|13,37|11,36|14,37|14,38|15,33|12,39|15,42|18,36|13,36|13,36|13,38|13,101|13,35|12,38|13,36|13,37|14,37|12,40|17,43|16,34|11,41|13,36|13,39|12,39|16,39|13,36|14,37|14,40|14,38|13,37|14,39|13,34|11,44|16,50|15,43|15,54|26,38|14,46|13,33|12,42|15,48|15,33|12,41|16,42|13,38|14,43|14,45|16,39|15,42|16,54|23,89|21,45|18,37|13,37|12,83|19,44|16,47|16,46|15,42|14,46|23,38|14,38|15,44|14,47|15,42|13,41|16,43|13,38|15,37|12,43|17,40|12,39|14,39|16,42|15,33|12,45|12,43|14,43|13,46|14,44|16,101|13,41|16,46|13,47|20,39|15,40|15,50|17,47|17,39|13,74|46,46|13,44|15,51|13,43|18,40|14,73|32,40|13,49|16,41|15,41|13,39|15,39|17,51|19,45|18,59|18,46|16,48|16,50|18,45|16,44|15,43|15,45|17,45|16,41|13,47|20,46|15,50|19,62|29,52|23,47|18,46|15,40|15,39|15,48|14,40|15,52|25,46|16,47|17,42|16,48|19,42|14,57|24,71|31,50|19,50|18,61|20,47|15,54|17,46|16,46|15,52|15,55|20,60|29,50|19,71|33,47|19,55|20,49|18,101|17,56|16,44|20,101|20,55|18,55|20]
    0.0% (    0 ms) MSUpdater msout.
```

**Comment by AlexKurek** [comment]
By looking at the plots I just noticed that also NGC 6946 is affected by this issue.
What is the proper version / commit of DP3 to use? Or is there a container image I could use? (I tried the recipe you linked aboce, but compilation crashes https://github.com/tikk3r/flocs/issues/56)

**Comment by tikk3r** [comment]
> By looking at the plots I just noticed that also NGC 6946 is affected by this issue. What is the proper version / commit of DP3 to use? Or is there a container image I could use? (I tried the recipe you linked above, but compilation crashes [tikk3r/flocs#56](https://github.com/tikk3r/flocs/issues/56))

You can find links to pre-built containers on https://tikk3r.github.io/flocs/. You probably want the 4.X version (3.X is for old genericpipeline support).

**Comment by AlexKurek** [comment]
I tried continer v4.0.2 like so:
```
singularity exec -B /storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/ /home/akurek/tikk3r/lofar_sksp_v4.0.2_x86-64_generic_noavx512_ddf.sif python ./lofar_facet_selfcal/facetselfcal.py \
	--auto \
	--helperscriptspath "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/lofar_facet_selfcal" \
	--helperscriptspathh5merge "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc" \
	--losotobeamcor-beamlib stationresponse \
	-b 4C29.30.ds9.reg \
	-i 4C29.30_facet_selfcal \
	--noarchive \
	MS0839.8+2938_4C29.30.dysco.sub.shift.avg.weights.ms.archive0 \
	> log_Facetselfcal_sing.txt 2>&1
```
 
It has DP3 version 5.4.0 (I have master version, so very close). Anyway, I got:
```
PREDICT STEP:  wsclean -size 1440 1440 -padding 1.8 -predict  -channels-out 6 -gridder wgridder -name 4C29.30_facet_selfcal_000 -scale 1.5arcsec MS0839.8+2938_4C29.30.dysco.sub.shift.avg.weights.ms.archive0.copy
INFO: Setting slices=[0, 0] [aplpy.core]
Traceback (most recent call last):
  File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 2906, in plotimage
    plotimage_astropy(fitsimagename,outplotname,mask,rmsnoiseimage)
  File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 2836, in plotimage_astropy
    ax = f.add_subplot(111,projection=WCS(head),slices=('x','y',0,0))
  File "/opt/lofar/pyenv-py3/lib64/python3.9/site-packages/matplotlib/figure.py", line 743, in add_subplot
    ax = projection_class(self, *args, **pkw)
TypeError: __init__() got multiple values for argument 'wcs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 6645, in <module>
    main()
  File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 6542, in main
    plotimage(plotfitsimage, plotpngimage, mask=fitsmask, rmsnoiseimage=plotfitsimage)
  File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 2908, in plotimage
    plotimage_aplpy(fitsimagename,outplotname,mask,rmsnoiseimage)
  File "/storage/akurek/extractPy/4C29.30/4C29.30/_facet_sc/./lofar_facet_selfcal/facetselfcal.py", line 2873, in plotimage_aplpy
    f = aplpy.FITSFigure(fitsimagename, slices=[0, 0])
  File "/opt/lofar/pyenv-py3/lib/python3.9/site-packages/aplpy/decorators.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/opt/lofar/pyenv-py3/lib/python3.9/site-packages/aplpy/core.py", line 267, in __init__
    self.ax = WCSAxesSubplot(self._figure, *subplot, wcs=self._wcs,
TypeError: __init__() got multiple values for argument 'wcs'
```
This error has never happened to me before.

In the log I see:
`Iterations taken: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]`

**Comment by tikk3r** [comment]
Could you try the specific DP3 commit `5dab4c43` locally? I notice the linked generic 4.0.2  container has a slightly newer commit compared to our local node-specific 4.0.2 container.

**Comment by rvweeren** [comment]
Be careful
> Iterations taken: [1,1,1,1,1,1,1,1,1 ..
might come from the "h5 template" solve (where maxiter=1). So that could be normal.

**Comment by AlexKurek** [comment]
Its still computing, but it seems now it will work:
`Iterations taken: [97|46,101|38,101|40,101|38,82|40,101|23,76|29,86|21,101|46,101|21,101|27,82|24,86|21,68|31,98|21,101|20,84|27,101|22,90|32,66| [...]`

**Comment by AlexKurek** [comment]
It worked for all 3 objects. The images are of comparable quality that from "standard" selfcal.

**Comment by AlexKurek** [comment]
I was able to compute all 3 fields, its not crashing now. Sice everyting it working, I think I should close thiss isue?

**Comment by AlexKurek** [comment]
@tikk3r I would have a question,
Do you know if this DP3 issue is fixed? Can we use master version now?
https://github.com/rvweeren/lofar_facet_selfcal/issues/65#issuecomment-1510280940
