### ISSUE TITLE
Unnecessary conflict with python 2 and early 3 versions

### ISSUE THREAD

**Issue by jwpetley** [rvweeren/lofar_facet_selfcal#71]
https://github.com/rvweeren/lofar_facet_selfcal/blob/b3968311272ab1dddb0dee3fd68469be2ac51dd4/facetselfcal.py#L6285

This copy is only a feature of later python3 versions and is not necessary in context as `mslist_tmp` is not used again in the code so preserving it doesn't add value. Could it be changed just to a variable assignment?

**Comment by rvweeren** [comment]
Yes, thanks for reporting. Should be fixed now.
