### ISSUE TITLE
getting it working with generic pipeline

### ISSUE THREAD

**Issue by lmorabit** [rvweeren/lofar_facet_selfcal#8]
I know that we're working towards CWL but there's still a need for this to be added to the current lofar-vlbi pipeline so people can use it in the meantime. There are a two things at the moment which are necessary for that:

1. the file facetselfcal.py should be executable (chmod +x) and git will preserve the permissions

2. this can either be run as an executable with a list of flags or it can be run as a pythonplugin with the arguments individually defined, e.g.:

```
delay_solve.control.type                        = pythonplugin
delay_solve.control.executable                  = {{ selfcal_dir }}/facetselfcal.py
delay_solve.control.mapfiles_in                 = [phaseup_concat.output.mapfile,delay_cal_model_map.output.mapfile]
delay_solve.control.inputkeys                   = [msin,skymod]
delay_solve.argument.flags                      = [msin]
delay_solve.argument.helperscriptspath          = {{ selfcal_dir }}
delay_solve.argument.helperscriptspath-h5merge  = {{ helper_dir }}
delay_solve.argument.imsize                     = 1600
delay_solve.argument.skymodel                   = skymod
delay_solve.argument.pixelscale                 = 0.075
----- etc.
```

It's a lot easier to work with the latter solution, since running it as an executable requires a list that will look something like:

[msin,'--helperscriptspath','/path/to/scripts/','--imsize','1600','...', .... ]

which will get really long as there are many elements, and can be tricky to keep updated. 

So turning to the other option, the script doesn't support being run as a pythonplugin because it has:

def main()

where the pipeline is expecting:

def main( msin, helpersciptspath=..., imsize=...,  etc.)

so it complains that the number of arguments don't match.

I understand that there are a very large number of arguments, which means that keeping the def main( ..... ) would be a pain.  

Is it possible to run this script with the arguments defined in a file, for example?

**Comment by rvweeren** [comment]
I think the easiest solution would be indeed to let it read things from a file.
